default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: recipe_app_development

test:
  <<: *default
  database: recipe_app_test

production:
  <<: *default
  database: recipe_app_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
